# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment # deployment name
  labels:
    name: my-nginx-deployment
  namespace: my-namespace # namespace
spec:
  replicas: 3 # number of replicas
  selector:
    matchLabels:
      app: my-nginx-deployment
  template:
    metadata:
      labels:
        app: my-nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.4
        ports:
        - containerPort: 80