# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod # pod name
  namespace: my-namespace # namespace
spec:
  containers:
  - name: my-nginx-container # container name
    image: nginx:1.29.4 # container image
    ports:
    - containerPort: 80 # container port