apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service # Service name
spec:
  selector:
    name: my-nginx-deployment # Selector to match pods
  type: ClusterIP # Service type
  ports:
  - name: http # Port name
    port: 8080 # Service port
    protocol: TCP # Protocol
    targetPort: 80 # Target port on the pod
