# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment # deployment name
  labels:
    name: myapi-deployment
  namespace: myapp-namespace # namespace
spec:
  replicas: 3 # number of replicas
  selector:
    matchLabels:
      app: myapi-deployment
  template:
    metadata:
      labels:
        app: myapi-deployment
    spec:
      containers:
      - name: cs-api
        image: tzather/cs-api:v1
        ports:
        - containerPort: 80